trigger:
- none
pool:
  vmImage: ubuntu-latest

parameters:
  - name: workspace
    type: string
    displayName: Please enter the workspace to deploy to
  - name: pattern
    type: string
    displayName: Please select the pattern to deploy


steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        cd patterns
        ls -ltr

  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'gcp'
      command: 'custom'
      customCommand: 'workspace '
      commandOptions: 'new ${{ parameters.workspace }}'
      outputTo: 'console'
      environmentServiceNameGCP: 'ado-terraform'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'gcp'
      command: 'custom'
      customCommand: 'workspace'
      commandOptions: 'select'
      outputTo: 'console'
      environmentServiceNameGCP: 'ado-terraform'

  
  
