trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: testvar1
    type: string
    values:
    - windows-latest
    - ubuntu-latest
    - macOS-latest
    default: ubuntu-latest

variables: 
  - name: testvar2
    value: initialVal
   
steps:
- script: echo ${{ parameters.testvar1}}
  displayName: 'Read parameter value'

- script: echo ${{ variables.testvar2}}
  displayName: 'Read parameter value 2'

- script: |
    echo "##vso[task.setvariable  variable=testvar2;] secondVal"
  displayName: 'Set parameter value'

- script: echo ${{ variables.testvar2}}
  displayName: 'Read parameter value 3'