trigger:
- none
pool:
  vmImage: ubuntu-latest

parameters:
  - name: workspace
    type: string
    displayName: Please enter the workspace to deploy to
  - name: pattern
    type: string
    displayName: Please select the pattern to deploy


steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        cd patterns
        ls -ltr

  
  
