name: "Terraform PR Check"

on:
  pull_request:
      branches:
        - main

env:
  TERRAFORM_DIR: patterns
  CCOE_DIR: patterns/1

jobs:
  vars:
    name: "Compute Variables"
    runs-on: ubuntu-latest
    outputs:
      terraform_dir: ${{ env.TERRAFORM_DIR }}
      ccoe_dir: ${{ env.CCOE_DIR }}
    steps:
      - run: echo "Exposing env vars"

  test_diff:
    uses: ./.github/workflows/test_diff.yaml
    needs: vars
    with: 
        dir: ${{ needs.vars.outputs.terraform_dir }}
 
  run_tests:
    name: "Run Terraform Tests"
    runs-on: ubuntu-latest
    needs: test_diff
    if: ${{ needs.test_diff.outputs.files_changed == 'true' }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Terraform Format Check
        id: FMT
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform fmt -recursive -check
        
      - name: Run Terraform Init
        working-directory: ${{ env.CCOE_DIR }}
        run: terraform init -backend=false
      
      - name: Run Terraform Validation Check
        id: Validate
        working-directory: ${{ env.CCOE_DIR }}
        run: terraform validate
     
      - name: Run Terraform Unit Tests 
        id: Unit_tests
        working-directory: ${{ env.CCOE_DIR }}
        run: terraform test

  # skipped:
  #     name: "Tests Skipped"
  #     runs-on: ubuntu-latest
  #     needs: test_diff
  #     if: ${{ needs.test_diff.outputs.files_changed == 'false' }}
  #     steps:
  #       - name: Dont Run Terraform Unit Tests 
  #         id: Unit_tests
  #         run: echo "NO TESTS TO RUN!"
      

