name: "Terraform PR Check"

on:
  pull_request:
    branches:
      - main
    paths:
      - patterns/**

jobs:
  terraform_fmt_check:
    name: "Terraform FMT Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run Terraform Format Check
        id: fmt
        run: |
          cd patterns
          terraform fmt -recursive -check

      - name: Run Terraform Validation Check
        id: validate
        run: |
          cd patterns
          terraform init
          terraform validate
