name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Move to dir
        run: |
          cd patterns

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
     
      - name: token
        id: token
        if: success() || failure()
        run: echo "${{ secrets.GITHUB_TOKEN }}"
