name: "Terraform"

on:
  pull_request:
    branches:
      - main
    paths:
      - patterns/**

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
          
      - name: Terraform Format
        id: fmt
        run: |
          cd patterns
          terraform fmt -recursive -check
