name: Reusable workflow example

on:
  pull_request:
    types: 
      - opened
      - reopend
      - edited
      - syncronized
    
jobs:
  test_diff:
    uses: ./.github/workflows/test_diff.yaml
    with: 
      dir: "./modules"

  testing:
    runs-on: ubuntu-latest
    needs: test_diff
    steps:
      # Run tests only if relevant changes were found
      - name: Run Tests
        if: ${{ needs.test_diff.outputs.changes }} == true
        run: |
          echo "Running tests for relevant changes."

      # Skip message
      - name: Skip Job
        if: ${{ needs.test_diff.outputs.changes }} == false
        run: echo "No relevant changes detected. Job skipped."

  example_cinditional:
    runs-on: ubuntu-latest
    needs: test_diff
    if: ${{ needs.test_diff.outputs.changes }} == true
    steps:
      # Run tests only if relevant changes were found
      - name: Run More Tests
        run: |
          echo "Running more tests for relevant changes."
