name: File Change Check

on:
  workflow_call: 
    inputs: 
      dir: 
        description: "The directory to check for changes, please make sure to append a trailing slash"
        type: string
        default: "example/folder/"
      extension: 
        description: "The type of file extension to check for"
        type: string
        default: "any"
    outputs:
      files_changed: 
        description: "Indicates if there have been any changes to files in the provided directory"
        value: ${{ jobs.dir-file-check.outputs.files_changed }}
      extension_changed:
        description: "Indicates if there have been any changes to files with the provided extension"
        value: ${{ jobs.dir-file-check.outputs.extension_changed }}
    

jobs:
  dir-file-check:
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.changes.outputs.files_changed }} 

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full commit history

      # Show changed files
      - name: Determine Changed Files
        id: diff
        run: |
          normal="\033[0m"
          green="\033[0;32m"
          yellow="\033[0;33m"
          
          BASE_BRANCH_SHA=${{ github.event.pull_request.base.sha }}
          BASE_BRANCH_REF=${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH_SHA=${{ github.event.pull_request.head.sha }}
          HEAD_BRANCH_REF=${{ github.event.pull_request.head.ref }}
          
          echo -e "${green}Comparing changes between:${normal}"
          echo -e "Base branch: ${yellow}$BASE_BRANCH_REF${normal} (SHA: $BASE_BRANCH_SHA)"
          echo -e "Head branch: ${yellow}$HEAD_BRANCH_REF${normal} (SHA: $HEAD_BRANCH_SHA)"
          
          # Use git diff to list changed files
          CHANGED_FILES=$(git diff --name-only $BASE_BRANCH_SHA $HEAD_BRANCH_SHA)
          echo -e "${green}Changed files:${normal}"
          echo "$CHANGED_FILES"

          # Set changed files as output in a single line so other steps can use it
          CHANGED_FILES_SINGLE_LINE=$(echo "$CHANGED_FILES" | tr '\n' ',')  # Converts newlines to commas
          echo "csf=${CHANGED_FILES_SINGLE_LINE}" >> $GITHUB_ENV
          UNIQUE_EXTENSIONS=$(echo "$CHANGED_FILES" | sed "s/.*\.//" | sort -u)
          echo "ext=$UNIQUE_EXTENSIONS" >> $GITHUB_env

      # Filter for changes in directory
      - name: Check for Directory Changes
        id: directory_changes
        env: 
          comma_separated_files: ${{ env.csf }}
          search_directory:  ${{ inputs.dir }}
          unique_extensions: ${{ env.ext }}
          search_extension: ${{ inputs.type }}
        run: |
          normal="\033[0m"
          green="\033[0;32m"
          
          echo -e "${green}Filtering files for the path: ${normal}$search_directory"
          
          if ! echo "$comma_separated_files" | grep -q "$search_directory"; then
            echo -e "${green}No changes found in ${normal}$search_directory."
            echo "files_changed=false" >> $GITHUB_OUTPUT
          else
            echo -e "${green}Changes found in ${normal}$search_directory"
            echo "files_changed=true" >> $GITHUB_OUTPUT
          fi
        
      - name: Check for Extension Changes
        id: extension_changes
        if: ${{ inputs.extension != 'any' }}
        env: 
          unique_extensions: ${{ env.ext }}
          search_extension: ${{ inputs.extension }}
        run: |
          normal="\033[0m"
          green="\033[0;32m"
          
          echo -e "${green}Filtering files for the extension: ${normal}$search_extension"

          if ! echo "$unique_extensions" | grep -q "$search_extension"; then
            echo -e "${green}No changes found in ${normal}$search_extension."
            echo "extension_changed=false" >> $GITHUB_OUTPUT
          else
            echo -e "${green}Changes found in ${normal}$search_extension"
            echo "extension_changed=true" >> $GITHUB_OUTPUT
          fi
