name: Deploy Resources
on:
  workflow_dispatch:
    inputs:
      role:
        description: Role to assume
        default: "deval"
        type: string

jobs:
  test_connection:
    runs-on: ubuntu-latest
    steps:
      - name: Should be automation-scheduler
        run: |
            echo "${{ github.event.inputs.role }}"
